name: Container Security Scan
on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'app/**'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
  workflow_dispatch: {}

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        working-directory: app
        run: |
          echo "🐳 Building Docker image for security scan..."
          docker build -t wiz-todo-app:scan .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'wiz-todo-app:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Run Trivy scanner (table format for logs)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'wiz-todo-app:scan'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
      
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './app'
          format: 'table'
          severity: 'CRITICAL,HIGH'