name: Kubernetes Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'demo'
        type: choice
        options:
        - demo
        - dev
        - staging
        - prod
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'
      - 'app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wiz-exercise-demo-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🐳 Building Docker image..."
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          echo "📤 Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Container Security Scan (SARIF)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ env.IMAGE_URI }}
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Container Security Scan (Table)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ env.IMAGE_URI }}
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
      
      - name: Update kubeconfig
        run: |
          echo "🔧 Configuring kubectl..."
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name wiz-exercise-demo
          
          # Test connection and show debug info
          echo "Testing kubectl connection..."
          kubectl get nodes || echo "Warning: kubectl connection test failed"
          
          # Show current context
          kubectl config current-context
          
          # Try alternative auth method if needed
          if ! kubectl get nodes; then
            echo "Trying alternative authentication..."
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name wiz-exercise-demo --role-arn $(aws sts get-caller-identity --query Arn --output text | sed 's/:user\//:role\//')
          fi
      
      - name: Update Kubernetes manifests
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
        run: |
          echo "📝 Updating Kubernetes manifests with new image..."
          
          # Update deployment with new image
          sed -i "s|image: .*|image: $IMAGE_URI|g" k8s/app/deployment.yaml
          
          # Update MongoDB IP if available (optional - app works without it)
          MONGODB_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=*mongodb*" "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text 2>/dev/null || echo "disabled")
          if [ "$MONGODB_IP" != "disabled" ] && [ -n "$MONGODB_IP" ]; then
            echo "Found MongoDB IP: $MONGODB_IP"
            sed -i "s|value: \"disabled\"|value: \"$MONGODB_IP\"|g" k8s/app/deployment.yaml
          else
            echo "MongoDB not found or disabled - app will run without database"
          fi
          
          # Update ingress with actual subnet IDs
          SUBNET_IDS=$(aws ec2 describe-subnets --filters "Name=tag:Name,Values=*wiz-exercise*public*" --query 'Subnets[*].SubnetId' --output text | tr '\t' ',')
          sed -i "s|alb.ingress.kubernetes.io/subnets: .*|alb.ingress.kubernetes.io/subnets: $SUBNET_IDS|g" k8s/app/ingress.yaml
          
          echo "Updated subnets: $SUBNET_IDS"
      
      - name: Deploy to Kubernetes
        run: |
          echo "🚀 Deploying to Kubernetes..."
          
          # Test kubectl connection first
          kubectl get nodes || echo "Warning: kubectl connection issues"
          
          # Apply RBAC first (creates service account with cluster-admin)
          kubectl apply -f k8s/app/rbac.yaml --validate=false
          
          # Apply service
          kubectl apply -f k8s/app/service.yaml --validate=false
          
          # Apply deployment
          kubectl apply -f k8s/app/deployment.yaml --validate=false
          
          # Apply ingress
          kubectl apply -f k8s/app/ingress.yaml --validate=false
          
          echo "✅ Deployment complete!"
      
      - name: Wait for deployment
        run: |
          echo "⏳ Waiting for deployment to be ready..."
          kubectl rollout status deployment/wiz-todo-app --timeout=300s
          
          echo "📊 Deployment status:"
          kubectl get pods -l app=wiz-todo-app
          kubectl get services -l app=wiz-todo-app
          kubectl get ingress
      
      - name: Verify deployment
        run: |
          echo "🔍 Verifying deployment..."
          
          # Check if pods are running
          READY_PODS=$(kubectl get pods -l app=wiz-todo-app --field-selector=status.phase=Running --no-headers | wc -l)
          echo "Ready pods: $READY_PODS"
          
          if [ "$READY_PODS" -gt 0 ]; then
            echo "✅ Deployment verification successful!"
            
            # Test the application
            POD_NAME=$(kubectl get pods -l app=wiz-todo-app --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}')
            echo "Testing wizexercise.txt file..."
            kubectl exec $POD_NAME -- cat /app/wizexercise.txt
            
            # Test health endpoint
            kubectl exec $POD_NAME -- wget -qO- http://localhost:3000/health || echo "Health check not available"
          else
            echo "❌ Deployment verification failed!"
            kubectl describe pods -l app=wiz-todo-app
            exit 1
          fi
      
      - name: Security validation
        run: |
          echo "🔒 Validating security configurations..."
          
          # Check RBAC over-privilege (should show cluster-admin access)
          echo "Checking service account permissions:"
          kubectl auth can-i --list --as=system:serviceaccount:default:wiz-todo-app-sa | head -10
          
          # Check if ALB is being created
          echo "Checking ingress status:"
          kubectl get ingress -o wide
          
          echo "🎯 Security validation complete - vulnerabilities ready for Wiz demo!"