name: Terraform Debug
on: 
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
      - uses: hashicorp/setup-terraform@v3
      
      - name: Check AWS Connection
        run: |
          echo "🔍 Testing AWS connection..."
          aws sts get-caller-identity
          echo "✅ AWS connection successful"
      
      - name: Check Terraform Files
        working-directory: terraform
        run: |
          echo "📁 Terraform files:"
          ls -la
          echo ""
          echo "🔍 Terraform format check:"
          terraform fmt -check -diff || echo "⚠️ Format issues found"
      
      - name: Terraform Init & Validate
        working-directory: terraform
        run: |
          echo "🚀 Terraform init..."
          terraform init
          echo ""
          echo "✅ Terraform validate..."
          terraform validate
      
      - name: Check for Existing Resources
        run: |
          echo "🔍 Checking for existing resources..."
          
          # Check EC2 instances
          echo "EC2 Instances:"
          aws ec2 describe-instances --filters "Name=tag:Project,Values=wiz-exercise-v4" --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0]]' --output table || echo "No instances found"
          
          # Check S3 buckets
          echo "S3 Buckets:"
          aws s3api list-buckets --query "Buckets[?contains(Name, 'wiz-exercise')].Name" --output table || echo "No buckets found"
          
          # Check VPCs
          echo "VPCs:"
          aws ec2 describe-vpcs --filters "Name=tag:Project,Values=wiz-exercise-v4" --query 'Vpcs[*].[VpcId,State,Tags[?Key==`Name`].Value|[0]]' --output table || echo "No VPCs found"
      
      - name: Terraform Plan (Dry Run)
        working-directory: terraform
        run: |
          echo "📋 Terraform plan (dry run)..."
          terraform plan -var="aws_region=${{ secrets.AWS_REGION }}" -detailed-exitcode || echo "Plan completed with changes or errors"